/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;



/**
 *
 * @author Janmel
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard(int id) {
        initComponents();
        this.userId = id;
        show_vehicle();
    }

    int userId;
    private Dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
   /* Dashboard(int id) {
        this.userId = id;
    }*/
    
    public ArrayList<vehicleDash> vehicleList(){
        ArrayList<vehicleDash> vehicleList = new ArrayList<>();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/service_db","root","");
            PreparedStatement ps;
            String query="SELECT * FROM vehicles where user_id=?";
            ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setInt(1,userId);
            ResultSet rs=ps.executeQuery();
            
            vehicleDash vehicle;
            while(rs.next()){
                vehicle=new vehicleDash(rs.getString("vehicle_model"), rs.getString("plate_number"), rs.getString("odometer"));
                vehicleList.add(vehicle);
            }
            
        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.out.println(e); 
        }
        return vehicleList;
    }
    
    
   public void show_vehicle(){
        ArrayList<vehicleDash> list = vehicleList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Vehicle.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getVehicle();
            row[1]=list.get(i).getPlate();
            row[2]=list.get(i).getOdometer();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        vehicle_model = new javax.swing.JTextField();
        odometer = new javax.swing.JTextField();
        plate_number = new javax.swing.JTextField();
        addOnClick = new javax.swing.JToggleButton();
        updateOnClick = new javax.swing.JToggleButton();
        deleteOnClick = new javax.swing.JToggleButton();
        searchOnClick = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_Vehicle = new javax.swing.JTable();
        reset_but = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(135, 88, 255));

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setBackground(new java.awt.Color(24, 24, 24));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(135, 88, 255));
        jLabel1.setText("Your Vehicles");

        jLabel3.setBackground(new java.awt.Color(24, 24, 24));
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Vehicle Model");

        jLabel4.setBackground(new java.awt.Color(24, 24, 24));
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Odometer");

        jLabel5.setBackground(new java.awt.Color(24, 24, 24));
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Plate Number");

        jSeparator1.setForeground(new java.awt.Color(135, 88, 255));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        odometer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odometerActionPerformed(evt);
            }
        });

        plate_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plate_numberActionPerformed(evt);
            }
        });

        addOnClick.setText("Add");
        addOnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOnClickActionPerformed(evt);
            }
        });

        updateOnClick.setText("Update");
        updateOnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOnClickActionPerformed(evt);
            }
        });

        deleteOnClick.setText("Delete");
        deleteOnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOnClickActionPerformed(evt);
            }
        });

        searchOnClick.setText("Search");
        searchOnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOnClickActionPerformed(evt);
            }
        });

        jTable_Display_Vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Model", "Plate Number", "Odometer"
            }
        ));
        jTable_Display_Vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_VehicleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_Display_VehicleMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Display_Vehicle);

        reset_but.setText("Reset");
        reset_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plate_number))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicle_model, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odometer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(updateOnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchOnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addOnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteOnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset_but)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addOnClick)
                        .addComponent(deleteOnClick))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(odometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(vehicle_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(plate_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateOnClick)
                        .addComponent(searchOnClick)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset_but)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchOnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOnClickActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/service_db","root","");
            PreparedStatement ps;
            String vm = vehicle_model.getText();
            String pn = plate_number.getText();
            String odo = odometer.getText();
            
            String query = "SELECT * FROM vehicles where vehicle_model=? AND plate_number=? AND odometer=? AND user_id=?";
            ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1,vm);
            ps.setString(2,pn);
            ps.setString(3,odo);
            ps.setInt(4,userId);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_Vehicle.getModel();
            Object[] row = new Object[3];
            model.setRowCount(0);
            for(int i=0;rs.next();i++){
            row[0]= rs.getString("vehicle_model");
            row[1]= rs.getString("plate_number");
            row[2]= rs.getString("odometer");
            model.addRow(row);
            }    
        }catch (Exception e) {
            System.err.println("Got an exception!");
            System.out.println(e); 
        }  
    }//GEN-LAST:event_searchOnClickActionPerformed

    private void deleteOnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOnClickActionPerformed
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/service_db","root","");
            PreparedStatement ps;
            int row = jTable_Display_Vehicle.getSelectedRow();
            String value = (jTable_Display_Vehicle.getModel().getValueAt(row, 1).toString());
            String value2 = (jTable_Display_Vehicle.getModel().getValueAt(row, 0).toString());
            String value3 = (jTable_Display_Vehicle.getModel().getValueAt(row, 2).toString());
            
            String query = "DELETE FROM vehicles where vehicle_model=? AND plate_number=? AND odometer=?";
            ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1,value2);
            ps.setString(2,value);
            ps.setString(3,value3);
            ps.execute();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_Vehicle.getModel();
            model.setRowCount(0);
            show_vehicle();
            System.err.println("im gone");
         }catch (Exception e) {
            System.err.println("Got an exception!");
            System.out.println(e); 
        }  
    }//GEN-LAST:event_deleteOnClickActionPerformed

    private void updateOnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOnClickActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/service_db","root","");
            PreparedStatement ps;
            int row = jTable_Display_Vehicle.getSelectedRow();
            String value = (jTable_Display_Vehicle.getModel().getValueAt(row, 1).toString());
            
            String query = "UPDATE vehicles SET vehicle_model=?, plate_number=?, odometer=? where plate_number=?";
            ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1,vehicle_model.getText());
            ps.setString(2,plate_number.getText());
            ps.setString(3,odometer.getText());
            ps.setString(4,value);
            ps.execute();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_Vehicle.getModel();
            model.setRowCount(0);
            show_vehicle();
            System.err.println("im here");
        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.out.println(e); 
        }
    }//GEN-LAST:event_updateOnClickActionPerformed

    private void addOnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOnClickActionPerformed
        int lastID = 0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/service_db","root","");
            PreparedStatement ps;

            String vm = vehicle_model.getText();
            String pn = plate_number.getText();
            String odo = odometer.getText();
            
            
            
            String query = "INSERT INTO vehicles(user_id,vehicle_model,plate_number,odometer)VALUES(?,?,?,?)";
            ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setInt(1,this.userId);
            ps.setString(2,vm);
            ps.setString(3,pn);
            ps.setString(4,odo);
            ps.execute();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_Vehicle.getModel();
            model.setRowCount(0);
            show_vehicle();
            System.err.println("im here");
            
            ResultSet rs = ps.getGeneratedKeys();
            if(rs.next()){
                lastID = rs.getInt(1);
            }
        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.out.println(e); 
        }
    }//GEN-LAST:event_addOnClickActionPerformed

    private void odometerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odometerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odometerActionPerformed

    private void plate_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plate_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plate_numberActionPerformed

    private void jTable_Display_VehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_VehicleMouseClicked
        int i = jTable_Display_Vehicle.getSelectedRow();
        TableModel model=jTable_Display_Vehicle.getModel();
        
        vehicle_model.setText(model.getValueAt(i, 0).toString());
        plate_number.setText(model.getValueAt(i, 1).toString());
        odometer.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_jTable_Display_VehicleMouseClicked
    
    private void reset_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_butActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Vehicle.getModel();
        model.setRowCount(0);
        show_vehicle();
    }//GEN-LAST:event_reset_butActionPerformed

    private void jTable_Display_VehicleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_VehicleMousePressed
        if(evt.getClickCount() == 2 && !evt.isConsumed()){
            try {
                evt.consume();
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/service_db","root","");
                PreparedStatement ps;
                
                String query = "SELECT vehicle_id FROM vehicles where vehicle_model=? AND plate_number=? AND odometer=? AND user_id=?";
                ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                ps.setString(1,vehicle_model.getText());
                ps.setString(2,plate_number.getText());
                ps.setString(3,odometer.getText());
                ps.setInt(4,userId);
                var result = ps.executeQuery();
                
                if(result.next()){
                    int id = result.getInt("vehicle_id");
                    VehicleService Service= new VehicleService(id);
                    Service.setVisible(true);
                    Service.pack();
                    Service.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    System.err.println("Double clicked!");
                }
            }catch (Exception e) {
            System.err.println("Got an exception!");
            System.out.println(e); 

            }
        }
    }//GEN-LAST:event_jTable_Display_VehicleMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addOnClick;
    private javax.swing.JToggleButton deleteOnClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_Display_Vehicle;
    private javax.swing.JTextField odometer;
    private javax.swing.JTextField plate_number;
    private javax.swing.JButton reset_but;
    private javax.swing.JToggleButton searchOnClick;
    private javax.swing.JToggleButton updateOnClick;
    private javax.swing.JTextField vehicle_model;
    // End of variables declaration//GEN-END:variables
}
